name: Sequelize config dev CI

on:
  pull_request:
    paths:
      - "config-sequelize/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  config-sequelize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Build config
        run: |
          cd config
          npm ci
          npm run pack:lib
          cp dist/recursyve-nestjs-config-*.tgz
          cd ../sequelize-config
          npm i ./recursyve-nestjs-config-*.tgz
      - name: Install dependencies
        working-directory: config-sequelize
        run: npm i
      - name: Run tests
        working-directory: config-sequelize
        run: npm run test
